### ISSUE TITLE
Hardware: Add the option to increase the output voltage of the beacon bus

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/eps2#16]
To increase or decrease the output voltage of the buses, a few componentes must be changed in each converter. To reach the desired output power on the radio of the beacon, its input voltage must be increased to 5,5 or 6 V (TBD).

The output voltage value can be increased by changing the value of L1, R4 and R6. Check the datasheet of the converter to define the new values.

![eps-beacon-converter](https://user-images.githubusercontent.com/5316364/90967690-5d159680-e4b9-11ea-89c8-54b584cb4dce.png)

Converter datasheet: [https://www.ti.com/lit/ds/symlink/tps54540-q1.pdf](https://www.ti.com/lit/ds/symlink/tps54540-q1.pdf)

**Comment by andrempmattos** [comment]
- Example circuit: (RLS=R6 and RHS=R5)

![image](https://user-images.githubusercontent.com/25351149/91777094-4d870380-ebc5-11ea-8663-c217f5416b54.png)

- The output in function of the RLS and RHS resistors:
![image](https://user-images.githubusercontent.com/25351149/91777047-32b48f00-ebc5-11ea-831c-2bf75104e183.png)

- Following the datasheet instructions and maintaining previous decisions: (in our circuit)
RLSbefore=R6=**11.5k** -> RLSafter=**11.5k** (Output=**5V**)
RHSbefore=R4=**60.4k** -> RLSafter=**74.75k** (Output=**6V**)
