### ISSUE TITLE
Hardware: Add final BOM file using the newer SpaceLab template

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/eps2#19]
Obs: Remeber to update schematics pdf and full pdf .
Obs2: Use [no variation] for the output file.

**Comment by YanAzer** [comment]
Generating the BOM it was discovered that two components were missing the Partnumber, image is displayed below:

![image](https://user-images.githubusercontent.com/40373964/92336143-d4c7f180-f073-11ea-85a9-307bfc42182e.png)

The cause of this bug probably is that the excel template uses the parameter "Partnumber" and not "Manufacturer Part Number", almost all components have these both parameters except the 3k3 and 47k resistors. Easiest solution would be adding a new parameter "Partnumber" to these few components, for the future it could be better if the teamplate actually tries to find both parameters.

Note: When using the "Part Search" or "Manufacturer Part Search" tool the default parameter linked is "Manufacturer Part Number".
