### ISSUE TITLE
Hardware: Increase the maximum current of the blocking diodes

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/eps2#44]
The current model has a maximum continuous current of 1 A. This value must be increased to at least 2 A (with 2 solar panels in parallel, the maximum nominal current can reach 1 A or more).

> Blocking diodes designator: D17 to D22

**Comment by YanAzer** [comment]
Is this issue still relevant? If i am not mistaken the solar panels already include these blocking diodes, can you guys confirm @mgm8  @andrempmattos? Found an option [SMD22WS-TP](https://www.digikey.com/en/products/detail/micro-commercial-co/SMD22WS-TP/8554705?s=N4IgjCBcpgbFoDGUBmBDANgZwKYBoQB7KAbRABYAGSgJnIgF0CAHAFyhAGVWAnASwB2AcxABfArACcCEMkjps%2BIqQqVJAZg0gmINh279hYgpPjRZqTLgLFIZKpXUB2ABzaW7SF16CR4kJJg5DJyCtbKduCwTgCsksE6el4GvsbgNIEhloo2KlTkLuTSiZ7ehn4EcC5mSNnhtmR0GWBuJfo%2BRv5gki7S5qFWSg0glO66pSmdoqJAA) anyway.

**Comment by mgm8** [comment]
Yes, most commercial solar panels already include blocking diodes. In the FM we will probably replace these diodes by 0R jumpers (or even remove it from the project). For now we can replace the part number, but we will have to think about removing it or not soon.
