### ISSUE TITLE
Hardware: Check if is necessary update the PC104 connector

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/eps2#7]

**Comment by YanAzer** [comment]
The current PC104 connector has the old partnumber (https://www.digikey.com/product-detail/en/samtec-inc/SSW-126-01-G-D/SAM1208-26-ND/1112032), same as previous EPS 1.0 module. By contrast the OBDH 2.0 uses the right PC104 partnumber (https://www.digikey.com/product-detail/en/samtec-inc/ESQ-126-39-G-D/SAM10462-ND/3601055). Changing only the partnumber should solve the bug.

The visual 3D models are simplayed below, the difference in height is noticeable. @andrempmattos 

![image](https://user-images.githubusercontent.com/40373964/87352819-133ca680-c532-11ea-96dc-2b855597971f.png)

**Comment by andrempmattos** [comment]
Component updated! Using SSW-126-01-G-D
