### ISSUE TITLE
Firmware: Develop the CSP server task

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/eps2#81]
Reference:
* [csp_server.h](https://github.com/spacelab-ufsc/obdh2/blob/master/firmware/app/tasks/csp_server.h)
* [csp_server.c](https://github.com/spacelab-ufsc/obdh2/blob/master/firmware/app/tasks/csp_server.c)

**Comment by AugustoVassoler** [comment]
69d73a21dfa7277e14bf0dda92dc7ef68b04a4a2

**Comment by AugustoVassoler** [comment]
Review the task priority, period and timeout at csp_server.h
